# Generated by Django 2.1.3 on 2018-11-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approve_comment',
            field=models.TextField(blank=True),
        ),
    ]
